[project]
name = "hotel_booking"
version = "0.1.0"
description = ""
authors = [
    {name = "ilyas13z",email = "ilyas13z@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=5.2.5,<6.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "ruff (>=0.12.8,<0.13.0)",
    "pytest (>=8.4.1,<9.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "pytest-django (>=4.11.1,<5.0.0)",
    "pre-commit (>=4.3.0,<5.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)"
]

[tool.poetry]
packages = [{include = "hotel_booking", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "hotel_booking.settings"
pythonpath = ["src"]


[tool.ruff]
line-length = 79
lint.select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
]
exclude = [
    "migrations",
    ".venv",
    "venv",
    "__pycache__",
]
target-version = "py311"
